name: ${name}
version: ${version}
main: nl.sundeep.vulcansmp.VulcanSMP
description: ${description}
api-version: "${apiVersion}"
load: STARTUP
authors:
  - Sundeep_

dependencies:
  server:
    Vault:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
    LuckPerms:
      required: false
      load: BEFORE
    WorldGuard:
      required: false
      load: BEFORE
    HeadDatabase:
      required: false
      load: BEFORE

permissions:
  vulcan.gamemode:
    description: Basis gamemode permissie
    default: op
  vulcan.gamemode.creative:
    description: Staat creative mode toe
    default: op
  vulcan.gamemode.survival:
    description: Staat survival mode toe
    default: op
  vulcan.gamemode.adventure:
    description: Staat adventure mode toe
    default: op
  vulcan.gamemode.spectator:
    description: Staat spectator mode toe
    default: op
  vulcan.gamemode.others:
    description: Staat toe om andermans gamemode te wijzigen
    default: op
  vulcan.fly:
    description: Staat fly command toe
    default: op
  vulcan.fly.others:
    description: Staat toe om fly voor anderen aan/uit te zetten
    default: op
  vulcan.teleport:
    description: Staat teleport command toe
    default: op
  vulcan.teleport.others:
    description: Staat toe om andere spelers te teleporteren
    default: op
  vulcan.tpa:
    description: Staat tpa command toe
    default: true
  vulcan.tpaccept:
    description: Staat toe om teleport verzoeken te accepteren
    default: true
  vulcan.tpadeny:
    description: Staat toe om teleport verzoeken te weigeren
    default: true
  vulcan.tpall:
    description: Staat toe om alle spelers te teleporteren
    default: op
  vulcan.back:
    description: Staat back command toe
    default: op
  vulcan.home:
    description: Staat home commands toe
    default: true
  vulcan.home.set:
    description: Staat toe om homes in te stellen
    default: true
  vulcan.home.delete:
    description: Staat toe om homes te verwijderen
    default: true
  vulcan.home.list:
    description: Staat toe om homes te bekijken
    default: true
  vulcan.home.unlimited:
    description: Staat onbeperkt aantal homes toe
    default: op
  vulcan.home.limit.*:
    description: Home limiet wildcard
    default: false
  vulcan.baltop:
    description: Staat baltop bekijken toe
    default: true
  vulcan.money.pay:
    description: Staat betalen aan andere spelers toe
    default: true
  vulcan.money.give:
    description: Staat geld geven aan spelers toe
    default: op
  vulcan.money.take:
    description: Staat geld afnemen van spelers toe
    default: op
  vulcan.money.set:
    description: Staat balans instellen toe
    default: op
  vulcan.warp:
    description: Staat warps gebruiken toe
    default: true
  vulcan.warp.list:
    description: Staat warps bekijken toe
    default: true
  vulcan.warp.create:
    description: Staat warps aanmaken toe
    default: op
  vulcan.warp.delete:
    description: Staat warps verwijderen toe
    default: op
  vulcan.heal:
    description: Staat jezelf healen toe
    default: op
  vulcan.heal.others:
    description: Staat andere spelers healen toe
    default: op
  vulcan.feed:
    description: Staat jezelf voeden toe
    default: op
  vulcan.feed.others:
    description: Staat andere spelers voeden toe
    default: op
  vulcan.weather:
    description: Staat weer wijzigen toe
    default: op
  vulcan.spawn:
    description: Staat spawn command toe
    default: true
  vulcan.setspawn:
    description: Staat spawn instellen toe
    default: op
  vulcan.removespawn:
    description: Staat spawn verwijderen toe
    default: op
  vulcan.broadcast:
    description: Staat broadcast berichten toe
    default: op
  vulcan.enderchest:
    description: Staat eigen enderchest bekijken toe
    default: op
  vulcan.enderchest.others:
    description: Staat andermans enderchest bekijken toe
    default: op
  vulcan.invsee:
    description: Staat andermans inventaris bekijken toe
    default: op
  vulcan.invsee.modify:
    description: Staat andermans inventaris wijzigen toe
    default: op
  vulcan.kit:
    description: Staat kits gebruiken toe
    default: true
  vulcan.kit.create:
    description: Staat kits aanmaken toe
    default: op
  vulcan.kit.delete:
    description: Staat kits verwijderen toe
    default: op
  vulcan.kit.bypass:
    description: Bypass kit cooldowns
    default: op
  vulcan.msg:
    description: Staat prive berichten sturen toe
    default: true
  vulcan.reply:
    description: Staat reply command toe
    default: true
  vulcan.playtime:
    description: Staat speeltijd bekijken toe
    default: true
  vulcan.playtime.others:
    description: Staat andermans speeltijd bekijken toe
    default: op
  vulcan.skull:
    description: Staat skull command toe
    default: op
  vulcan.vanish:
    description: Staat vanish toe
    default: op
  vulcan.vanish.see:
    description: Staat toe om vanished spelers te zien
    default: op
  vulcan.discord:
    description: Staat discord command toe
    default: true
  vulcan.store:
    description: Staat store command toe
    default: true
  vulcan.vote:
    description: Staat vote command toe
    default: true
  vulcan.friend:
    description: Staat friend commands toe
    default: true
  vulcan.staff:
    description: Markeert speler als staff
    default: op
